"""
     Paragraph('Задание', style=s_b),
     Paragraph('Разработать структурную схему КЭС на газомазутном топливе. Рассмотреть возможные варианты '
               'структурной схемы электростанции и для каждого из них выбрать номинальные параметры основного '
               'силового оборудования', style=s_m),
     Paragraph('Исходные данные:', style=s_b),
     Paragraph('Установленная мощность, МВт', style=st_0_10),
     img(f'$S = {p_st}$'),
     # Paragraph('Число генераторов', style=s_f_20),
     # img(f'$n_г = {n_g}$'),
     Paragraph('Генераторы, число и ном. мощность (МВт), расход на СН', style=s_f_10),
     img(f'${n_g} \\times {p_g}, {k_s_n*100:.0f}\\%$'),
     # Paragraph(f'Коэффициенты мощности (cos φ) генераторов, механизмов собственных нужд и '
     #           f'источников аварийного резерва энергосистемы одинаковые и равны 0.85'),
     # Paragraph('Нагрузки потребителей', style=st_i_5_5),
     Paragraph('Номинальное напряжение потребителей, кВ', style=s_f_10),
     img(f'$U = {u_ld}$'),
     # Paragraph('Число потребителей и максимальная мощность в зимний период, МВт', style=s_f_20),
     Paragraph('Число потребителей и максимальная мощность, МВт', style=s_f_10),
     img(f'${n_ld} \\times {p_ld}$'),
     Paragraph('Коэффициент мощности потребителей, о. е.', style=s_f_10),
     img(f'$cos\\phi = {cos_ld}$'),
     # Paragraph('Коэффициент одновременности', style=s_f_20),
     # img(f'$k_о = {k_s}$'),
     # Paragraph('Коэффициент летнего минимума', style=s_f_20),
     # img(f'$k_{{л.min}} = {k_min}$'),
     # Paragraph('Коэффициент летнего максимума', style=s_f_20),
     # img(f'$k_{{л.max}} = {k_sum_max}$'),
     # Paragraph('Число часов использования максимума нагрузки', style=s_f_20),
     # img(f'$T_{{max}} = {t_max}$'),
     # Paragraph('Система (сторона ВН)', style=st_i_5_5),
     Paragraph('Номинальное напряжение системы (стороны ВН), кВ', style=s_f_10),
     img(f'$U = {u_s}$'),
     Paragraph('Длина линий связи, км', style=s_f_10),
     img(f'$L = {l_ln}$'),
     Paragraph('Мощность аварийного резерва, МВт', style=s_f_10),
     img(f'$S_{{ав.рез.}} = {s_r}$'),
     Paragraph('Выбор генератора', style=st_b_10_2),
     Paragraph('Выбираем генератор Т3В-800-2У3 со следующими электрическими параметрами:', style=s_m),
     # Paragraph('Выбираем генератор ТВВ-800-2ЕКУ3 со следующими параметрами:', style=s_b),
     # Table(data, colWidths=[1.9*cm] + [None] * (len(data[-1])- 1),
     #       style=[('GRID', (0,0), (-1,-1), 1,colors.black)], hAlign='CENTER')
     # Table(data = [[img(f'$P_г$, МВт'), img(f'$S_г$, МВА'), img(f'$U_{{н.г}}$, кВ'),
     #         Paragraph('Схема соединения обмоток', style=s_m), img(f'${{x\'\'}}_d$, о.е.'),
     #                img(f'${{x\'}}_d$, о.е.'), img(f'$x_d$, о.е.'), img(f'$\\cos \\phi$, о.е.')],
     #        [img(f'${p_g}$'), img(f'${s_g_c}$'), img(f'${u_g}$'), Paragraph('Y/Y', style=s_m), img(f'${x_d__}$'),
     #         img(f'${x_d_}$'), img(f'${x_d}$'), img(f'${cos_g}$')]],
     #       style=[('GRID', (0,0), (-1,-1), 1,colors.black)], hAlign='CENTER')
# colWidths=50, rowHeights=20, spaceBefore=10, spaceAfter=20,
# Table(data, colWidths=[1.9*cm] + [None] * (len(data[-1])- 1),
     #       style=[('GRID', (0,0), (-1,-1), 1,colors.black)], hAlign='CENTER')
     # Table(data = [[img(f'$P_Г$, МВт'), img(f'$U_{{Г}}$, кВ'), img(f'$\\cos \\phi$, о.е.'), img(f'$S_Г$, МВА'),
     #         img(f'$Q_г = S_г \\cdot \\sin\\phi_г$, о.е.'), img(f'$I_г$, кА'), img(f'${{x\'\'}}_d$, о.е.'),
     #                img(f'${{x\'}}_d$, о.е.'), img(f'$x_d$, о.е.')],
     #        [img(f'${p_g}$'), img(f'${u_g}$'), img(f'${s_g}$'), img(f'${cos_g}$'), img(f'${q_g}$'), img(f'${i_g}$'),
     #         img(f'${x_d__}$'), img(f'${x_d_}$'), img(f'${x_d}$')]],
     #       style=[('GRID', (0,0), (-1,-1), 1, colors.black)], hAlign='CENTER'),
           Table(data = [[img(f'$P_Г$, МВт'), img(f'$U_Г$, кВ'), img(f'$\\cos \\phi$, о.е.'), img(f'$S_Г$, МВА'),
                          img(f'$Q_Г$, МВА'), img(f'$I_Г$, МВА')],
                         [img(f'${p_g}$'), img(f'${u_g}$'), img(f'${cos_g}$'), img(f'${s_g}$'),
                          img(f'${q_g:.1f}$'), img(f'${i_g}$')]], colWidths=70, rowHeights=20, spaceBefore=5,
                 spaceAfter=5, style=[('GRID', (0,0), (-1,-1), 1,colors.black)]),
     # , ('ALIGN', (0, 0), (-1, -1), "CENTER") выравнивание элементов в таблице по ширине
     """
